name: Continuous Delivery

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  CD:

    runs-on: ubuntu-latest
    env:
      PKG_VERSION: '1.0.3'

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Check for encoding of scrambled file
      run: file -bi ./ItalianSyllabary/ItalianSyllabaryTests/Manual/SimpleTests.cs
    - name: Change encoding of scrambled files
      run: |
        iconv -f iso-8859-1 -t utf-8 ./ItalianSyllabary/ItalianSyllabaryTests/Manual/SimpleTests.cs > ./ItalianSyllabary/ItalianSyllabaryTests/Manual/SimpleTests.cs && iconv -f iso-8859-1 -t utf-8 ./ItalianSyllabary/ItalianSyllabaryTests/Online/SimpleTests.cs > ./ItalianSyllabary/ItalianSyllabaryTests/Online/SimpleTests.cs && 
        iconv -f iso-8859-1 -t utf-8 ./ItalianSyllabary/ItalianSyllabaryTests/Manual/MassiveTests.cs > ./ItalianSyllabary/ItalianSyllabaryTests/Manual/MassiveTests.cs && iconv -f iso-8859-1 -t utf-8 ./ItalianSyllabary/ItalianSyllabaryTests/Online/MassiveTests.cs > ./ItalianSyllabary/ItalianSyllabaryTests/Online/MassiveTests.cs
    - name: Restore dependencies
      run: dotnet restore ./ItalianSyllabary/ItalianSyllabary.sln
    - name: Build
      run: dotnet build --no-restore ./ItalianSyllabary/ItalianSyllabary.sln
    - name: Test
      run: dotnet test --no-build --verbosity normal ./ItalianSyllabary/ItalianSyllabary.sln
    - name: Create package
      run: dotnet pack -p:PackageVersion=${PKG_VERSION} --configuration Release ./ItalianSyllabary/ItalianSyllabary/ItalianSyllabary.csproj
    - name: Publish package
      env:
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
      run: dotnet nuget push --api-key $NUGET_API_KEY /home/runner/work/ItalianSyllabary/ItalianSyllabary/ItalianSyllabary/ItalianSyllabary/bin/Release/ItalianSyllabary.${PKG_VERSION}.nupkg --source https://api.nuget.org/v3/index.json
      
