name: Test Library

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore ./ItalianSyllabary/ItalianSyllabary.sln
    - name: Test
      run: dotnet test --verbosity normal ./ItalianSyllabary/ItalianSyllabary.sln
