name: Test Library

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Check for encoding of incriminated file
      run: file -bi ./ItalianSyllabary/ItalianSyllabaryTests/Manual/SimpleTests.cs
    - name: Change encoding of incriminated files
      run: iconv -f iso-8859-1 -t utf-8 ./ItalianSyllabary/ItalianSyllabaryTests/Manual/SimpleTests.cs > ./ItalianSyllabary/ItalianSyllabaryTests/Manual/SimpleTests.cs && iconv -f iso-8859-1 -t utf-8 ./ItalianSyllabary/ItalianSyllabaryTests/Online/SimpleTests.cs > ./ItalianSyllabary/ItalianSyllabaryTests/Online/SimpleTests.cs
    - name: Restore dependencies
      run: dotnet restore ./ItalianSyllabary/ItalianSyllabary.sln
    - name: Test
      run: dotnet test --verbosity normal ./ItalianSyllabary/ItalianSyllabary.sln
    - name: Create package
      run: dotnet pack --configuration Release ./ItalianSyllabary/ItalianSyllabary/ItalianSyllabary.csproj
    - name: Publish package
      env:
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }} 
      run: dotnet nuget push --api-key $NUGET_API_KEY
      
